"""
Django settings for MeroDesh project.  
Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=@3viw)(-bm7!l3e3$wj#n(gxail(8k45l*h3u_*3(s9+96em+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'support@udghos.com'
EMAIL_HOST_PASSWORD='udghosnepal235'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

'''
# secrets
FACEBOOK_APP_ID       = '1652950188302583'
FACEBOOK_API_SECRET   = '990a6074547ba3f24f625d71df5a74dd'

TWITTER_CONSUMER_KEY = 'GYl0ArIVOoc6Gv0AZ3PXgubzJ'
TWITTER_CONSUMER_SECRET = 'VptaqoNhE56hXqEdp23AdJTEkVtWa8I3rQ0gFvnfA42HsR3DmQ'

GOOGLE_OAUTH2_CLIENT_ID = '79811044211-sh17bc48d064afgth0qum1ltar9jaqc0.apps.googleusercontent.com'
GOOGLE_OAUTH2_CLIENT_SECRET = 'EmlDdAQXHgGfr78U23_1KQBb'
'''


SOCIAL_AUTH_FACEBOOK_KEY = '1652950188302583'
SOCIAL_AUTH_FACEBOOK_SECRET = '990a6074547ba3f24f625d71df5a74dd'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY ='79811044211-sh17bc48d064afgth0qum1ltar9jaqc0.apps.googleusercontent.com' 
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'EmlDdAQXHgGfr78U23_1KQBb'

SOCIAL_AUTH_TWITTER_KEY = 'GYl0ArIVOoc6Gv0AZ3PXgubzJ'
SOCIAL_AUTH_TWITTER_SECRET = 'VptaqoNhE56hXqEdp23AdJTEkVtWa8I3rQ0gFvnfA42HsR3DmQ'

# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'social_auth',
    'social.apps.django_app.default',
    'complain',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)


AUTHENTICATION_BACKENDS = (
    'social.backends.twitter.TwitterOAuth',
    'social.backends.facebook.FacebookOAuth2',
    'social.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_procesors.auth',
    #'social_auth.context_processors.social_auth_by_type_backends'
    'social.apps.django_app.context_processors.backends',
    'social.apps.django_app.context_processors.login_redirect',
)

# pipeline
SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.mail.mail_validation',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.debug.debug',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
    'social.pipeline.debug.debug',
    'complain.pipeline.create_account',
)


#login urls
LOGIN_URL          = '/login/'
LOGIN_REDIRECT_URL          = '/complain/'
LOGIN_ERROR_URL ='/complain/error/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/complain/'

ROOT_URLCONF = 'MeroDesh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MeroDesh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
